package de.avgl.dmp.controller.resources;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import de.avgl.dmp.controller.resources.utils.BasicIDResourceUtils;
import de.avgl.dmp.controller.status.DMPStatus;
import de.avgl.dmp.persistence.model.BasicDMPJPAObject;
import de.avgl.dmp.persistence.model.DMPJPAObject;
import de.avgl.dmp.persistence.service.BasicIDJPAService;
import de.avgl.dmp.persistence.util.DMPPersistenceUtil;

/**
 * A generic resource (controller service) implementation for {@link BasicDMPJPAObject}s, i.e., objects where the identifier will
 * be generated by the database and that can have a name.
 * 
 * @author tgaengler
 * @param <POJOCLASSPERSISTENCESERVICE> the concrete persistence service of the resource that is related to the concrete POJO
 *            class
 * @param <POJOCLASS> the concrete POJO class of the resource
 */
public abstract class BasicIDResource<POJOCLASSRESOURCEUTILS extends BasicIDResourceUtils<POJOCLASSPERSISTENCESERVICE, POJOCLASS>, POJOCLASSPERSISTENCESERVICE extends BasicIDJPAService<POJOCLASS>, POJOCLASS extends DMPJPAObject>
		extends BasicResource<POJOCLASSRESOURCEUTILS, POJOCLASSPERSISTENCESERVICE, POJOCLASS, Long> {

	private static final org.apache.log4j.Logger	LOG	= org.apache.log4j.Logger.getLogger(BasicIDResource.class);

	/**
	 * Creates a new resource (controller service) for the given concrete POJO class with the provider of the concrete persistence
	 * service, the object mapper and metrics registry.
	 * 
	 * @param clasz a concrete POJO class
	 * @param persistenceServiceProviderArg the concrete persistence service that is related to the concrete POJO class
	 * @param objectMapperArg an object mapper
	 * @param dmpStatusArg a metrics registry
	 */
	public BasicIDResource(final POJOCLASSRESOURCEUTILS pojoClassResourceUtilsArg, final DMPStatus dmpStatusArg) {

		super(pojoClassResourceUtilsArg, dmpStatusArg);
	}

	@Override
	protected void checkObjectId(final JsonNode idNode, final ObjectNode objectJSON) {

		if (idNode.canConvertToLong()) {

			final long longId = idNode.asLong();

			if (longId < 0) {

				addDummyIdCandidate(Long.valueOf(longId));
			}
		}
	}

	@Override
	protected ObjectNode addDummyId(final ObjectNode objectJSON) {

		final long randomDummyId = DMPPersistenceUtil.generateRandomDummyId();

		// add dummy id to object
		objectJSON.put("id", randomDummyId);

		return objectJSON;
	}
}
