ALTER TABLE DATA_MODEL
	DROP FOREIGN KEY FK_DATA_MODEL_DATA_SCHEMA;

ALTER TABLE DATA_MODEL
	DROP FOREIGN KEY FK_DATA_MODEL_CONFIGURATION;

ALTER TABLE DATA_MODEL
	DROP FOREIGN KEY FK_DATA_MODEL_DATA_RESOURCE;

ALTER TABLE DATA_SCHEMA
	DROP FOREIGN KEY FK_DATA_SCHEMA_CONTENT_SCHEMA;

ALTER TABLE DATA_SCHEMA
	DROP FOREIGN KEY FK_DATA_SCHEMA_RECORD_CLASS;

ALTER TABLE COMPONENT
	DROP FOREIGN KEY FK_COMPONENT_TRANSFORMATION;

ALTER TABLE COMPONENT
	DROP FOREIGN KEY FK_COMPONENT_FUNCTION;

ALTER TABLE MAPPING
	DROP FOREIGN KEY FK_MAPPING_OUTPUT_ATTRIBUTE_PATH;

ALTER TABLE MAPPING
	DROP FOREIGN KEY FK_MAPPING_TRANSFORMATION;

ALTER TABLE PROJECT
	DROP FOREIGN KEY FK_PROJECT_OUTPUT_DATA_MODEL;

ALTER TABLE PROJECT
	DROP FOREIGN KEY FK_PROJECT_INPUT_DATA_MODEL;

ALTER TABLE PROJECT
	DROP FOREIGN KEY FK_PROJECT_SKIP_FILTER;

ALTER TABLE TRANSFORMATION
	DROP FOREIGN KEY FK_TRANSFORMATION_UUID;

ALTER TABLE ATTRIBUTE_PATH_INSTANCE
	DROP FOREIGN KEY FK_ATTRIBUTE_PATH_INSTANCE_ATTRIBUTE_PATH;

ALTER TABLE MAPPING_ATTRIBUTE_PATH_INSTANCE
	DROP FOREIGN KEY FK_MAPPING_ATTRIBUTE_PATH_INSTANCE_UUID;

ALTER TABLE MAPPING_ATTRIBUTE_PATH_INSTANCE
	DROP FOREIGN KEY FK_MAPPING_ATTRIBUTE_PATH_INSTANCE_FILTER;

ALTER TABLE SCHEMA_ATTRIBUTE_PATH_INSTANCE
	DROP FOREIGN KEY FK_SCHEMA_ATTRIBUTE_PATH_INSTANCE_UUID;

ALTER TABLE SCHEMA_ATTRIBUTE_PATH_INSTANCE
	DROP FOREIGN KEY FK_SCHEMA_ATTRIBUTE_PATH_INSTANCE_SUB_SCHEMA;

ALTER TABLE CONTENT_SCHEMA
	DROP FOREIGN KEY FK_CONTENT_SCHEMA_RECORD_IDENTIFIER_ATTRIBUTE_PATH;

ALTER TABLE CONTENT_SCHEMA
	DROP FOREIGN KEY FK_CONTENT_SCHEMA_VALUE_ATTRIBUTE_PATH;

ALTER TABLE CONFIGURATIONS_RESOURCES
	DROP FOREIGN KEY FK_CONFIGURATIONS_RESOURCES_CONFIGURATION_UUID;

ALTER TABLE CONFIGURATIONS_RESOURCES
	DROP FOREIGN KEY FK_CONFIGURATIONS_RESOURCES_RESOURCE_UUID;

ALTER TABLE ATTRIBUTE_PATHS_ATTRIBUTES
	DROP FOREIGN KEY FK_ATTRIBUTE_PATHS_ATTRIBUTES_ATTRIBUTE_PATH_UUID;

ALTER TABLE ATTRIBUTE_PATHS_ATTRIBUTES
	DROP FOREIGN KEY FK_ATTRIBUTE_PATHS_ATTRIBUTES_ATTRIBUTE_UUID;

ALTER TABLE SCHEMAS_SCHEMA_ATTRIBUTE_PATH_INSTANCES
	DROP FOREIGN KEY SCHMSSCHMTTRBTPATHINSTANCESSCHMTTRBTPTHNSTANCEUUID;

ALTER TABLE SCHEMAS_SCHEMA_ATTRIBUTE_PATH_INSTANCES
	DROP FOREIGN KEY SCHEMAS_SCHEMA_ATTRIBUTE_PATH_INSTANCESSCHEMA_UUID;

ALTER TABLE INPUT_COMPONENTS_OUTPUT_COMPONENTS
	DROP FOREIGN KEY INPUTCOMPONENTSOUTPUTCOMPONENTSOUTPUTCOMPONENTUUID;

ALTER TABLE INPUT_COMPONENTS_OUTPUT_COMPONENTS
	DROP FOREIGN KEY INPUTCOMPONENTSOUTPUTCOMPONENTSINPUTCOMPONENT_UUID;

ALTER TABLE MAPPINGS_INPUT_ATTRIBUTE_PATHS
	DROP FOREIGN KEY FK_MAPPINGS_INPUT_ATTRIBUTE_PATHS_MAPPING_UUID;

ALTER TABLE MAPPINGS_INPUT_ATTRIBUTE_PATHS
	DROP FOREIGN KEY MAPPINGSINPUTATTRIBUTEPATHSINPUTATTRIBUTEPATH_UUID;

ALTER TABLE PROJECTS_FUNCTIONS
	DROP FOREIGN KEY FK_PROJECTS_FUNCTIONS_PROJECT_UUID;

ALTER TABLE PROJECTS_FUNCTIONS
	DROP FOREIGN KEY FK_PROJECTS_FUNCTIONS_FUNCTION_UUID;

ALTER TABLE PROJECTS_MAPPINGS
	DROP FOREIGN KEY FK_PROJECTS_MAPPINGS_PROJECT_UUID;

ALTER TABLE PROJECTS_MAPPINGS
	DROP FOREIGN KEY FK_PROJECTS_MAPPINGS_MAPPING_UUID;

ALTER TABLE CONTENT_SCHEMAS_KEY_ATTRIBUTE_PATHS
	DROP FOREIGN KEY CONTENTSCHEMASKEYATTRIBUTEPATHSATTRIBUTE_PATH_UUID;

ALTER TABLE CONTENT_SCHEMAS_KEY_ATTRIBUTE_PATHS
	DROP FOREIGN KEY CONTENTSCHEMASKEYATTRIBUTEPATHSCONTENT_SCHEMA_UUID;

DROP TABLE RESOURCE;

DROP TABLE CONFIGURATION;

DROP TABLE DATA_MODEL;

DROP TABLE ATTRIBUTE;

DROP TABLE ATTRIBUTE_PATH;

DROP TABLE CLASS;

DROP TABLE DATA_SCHEMA;

DROP TABLE COMPONENT;

DROP TABLE FILTER;

DROP TABLE FUNCTION;

DROP TABLE MAPPING;

DROP TABLE PROJECT;

DROP TABLE TRANSFORMATION;

DROP TABLE ATTRIBUTE_PATH_INSTANCE;

DROP TABLE MAPPING_ATTRIBUTE_PATH_INSTANCE;

DROP TABLE SCHEMA_ATTRIBUTE_PATH_INSTANCE;

DROP TABLE CONTENT_SCHEMA;

DROP TABLE CONFIGURATIONS_RESOURCES;

DROP TABLE ATTRIBUTE_PATHS_ATTRIBUTES;

DROP TABLE SCHEMAS_SCHEMA_ATTRIBUTE_PATH_INSTANCES;

DROP TABLE INPUT_COMPONENTS_OUTPUT_COMPONENTS;

DROP TABLE MAPPINGS_INPUT_ATTRIBUTE_PATHS;

DROP TABLE PROJECTS_FUNCTIONS;

DROP TABLE PROJECTS_MAPPINGS;

DROP TABLE CONTENT_SCHEMAS_KEY_ATTRIBUTE_PATHS;
