/**
 * Copyright (C) 2013, 2014 SLUB Dresden & Avantgarde Labs GmbH (<code@dswarm.org>)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.dswarm.persistence.model.proxy;

import javax.xml.bind.annotation.XmlRootElement;

import org.dswarm.persistence.model.DMPJPAObject;

/**
 * The abstract proxy POJO class for entities where the identifier of the real object should be generated by the utilised
 * database.
 * 
 * @author tgaengler
 */
@XmlRootElement
public abstract class ProxyDMPJPAObject<POJOCLASS extends DMPJPAObject> extends ProxyDMPObject<POJOCLASS, Long> {

	/**
	 *
	 */
	private static final long	serialVersionUID	= 1L;

	/**
	 * Default constructor for handing over a freshly created object, i.e., no updated or already existing object.
	 * 
	 * @param dmpJPAObjectArg a freshly created object
	 */
	public ProxyDMPJPAObject(final POJOCLASS dmpJPAObjectArg) {

		super(dmpJPAObjectArg);
	}

	/**
	 * Creates a new proxy with the given real object and the type how the object was processed by the persistence service, e.g.,
	 * {@link RetrievalType.CREATED}.
	 * 
	 * @param dmpJPAObjectArg an object that was processed by a persistence service
	 * @param typeArg the type how this object was processed by the persistence service
	 */
	public ProxyDMPJPAObject(final POJOCLASS dmpJPAObjectArg, final RetrievalType typeArg) {

		super(dmpJPAObjectArg, typeArg);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long getId() {

		if (dmpObject == null) {

			return null;
		}

		return dmpObject.getId();
	}
}
