/**
 * Copyright (C) 2013 – 2017 SLUB Dresden & Avantgarde Labs GmbH (<code@dswarm.org>)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.dswarm.persistence.model;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import javax.xml.bind.annotation.XmlRootElement;

import com.google.common.base.Objects;

/**
 * An abstract POJO class for entities with a name, a description and where the identifier should be generated by the database.
 *
 * @author tgaengler
 */
@XmlRootElement
@MappedSuperclass
public abstract class ExtendedBasicDMPJPAObject extends BasicDMPJPAObject {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * A description of the entity.
	 */
	@Column(name = "DESCRIPTION", columnDefinition = "VARCHAR(4000)", length = 4000)
	private String description;

	public ExtendedBasicDMPJPAObject(final String uuidArg) {

		super(uuidArg);
	}

	protected ExtendedBasicDMPJPAObject() {

	}

	/**
	 * Gets the description of the entity.
	 *
	 * @return the description of the entity
	 */
	public String getDescription() {

		return description;
	}

	/**
	 * Sets the description of the entity
	 *
	 * @param description the description of the entity
	 */
	public void setDescription(final String description) {

		this.description = description;
	}

	@Override
	public boolean completeEquals(final Object obj) {

		return ExtendedBasicDMPJPAObject.class.isInstance(obj) && super.completeEquals(obj)
				&& Objects.equal(((ExtendedBasicDMPJPAObject) obj).getDescription(), getDescription());
	}
}
