package de.avgl.dmp.persistence.model;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.xml.bind.annotation.XmlID;

/**
 * The abstract POJO class for entities where the identifier should be generated by the utilised database.
 * 
 * @author tgaengler
 */
@MappedSuperclass
// @JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="id")
public abstract class DMPJPAObject extends DMPObject<Long> {

	/**
	 *
	 */
	private static final long	serialVersionUID	= 1L;

	/**
	 * The identifier of the entity.
	 */
	@Id
	@XmlID
	@Access(AccessType.FIELD)
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID")
	private Long				id;

	@Override
	public Long getId() {

		return id;
	}

	@Override
	public boolean completeEquals(final Object obj) {

		return DMPJPAObject.class.isInstance(obj) && super.completeEquals(obj);
	}

}
