package de.avgl.dmp.persistence.model;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import javax.xml.bind.annotation.XmlRootElement;

import com.google.common.base.Objects;

/**
 * An abstract POJO class for entities with a name, a description and where the identifier should be generated by the database.
 * 
 * @author tgaengler
 */
@XmlRootElement
@MappedSuperclass
public abstract class ExtendedBasicDMPJPAObject extends BasicDMPJPAObject {

	/**
	 *
	 */
	private static final long	serialVersionUID	= 1L;

	/**
	 * A description of the entity.
	 */
	@Column(name = "DESCRIPTION", columnDefinition = "VARCHAR(4000)", length = 4000)
	private String				description;

	/**
	 * Gets the description of the entity.
	 * 
	 * @return the description of the entity
	 */
	public String getDescription() {

		return description;
	}

	/**
	 * Sets the description of the entity
	 * 
	 * @param description the description of the entity
	 */
	public void setDescription(final String description) {

		this.description = description;
	}

	@Override
	public boolean completeEquals(final Object obj) {

		return ExtendedBasicDMPJPAObject.class.isInstance(obj) && super.completeEquals(obj) && Objects.equal(((ExtendedBasicDMPJPAObject) obj).getDescription(), getDescription());
	}
}
