package de.avgl.dmp.persistence.service;

import javax.persistence.EntityManager;

import com.google.inject.Provider;

import de.avgl.dmp.persistence.DMPPersistenceException;
import de.avgl.dmp.persistence.model.BasicDMPJPAObject;

/**
 * A generic persistence service implementation for {@link BasicDMPJPAObject}s, i.e., objects where the identifier will be
 * generated by the database and that can have a name.
 * 
 * @author tgaengler
 * @param <POJOCLASS> the concrete POJO class
 */
public abstract class BasicDMPJPAService<POJOCLASS extends BasicDMPJPAObject> extends BasicIDJPAService<POJOCLASS> {

	/**
	 * Creates a new persistence service for the given concrete POJO class and the entity manager provider.
	 * 
	 * @param clasz a concrete POJO class
	 * @param entityManagerProvider an entity manager provider
	 */
	protected BasicDMPJPAService(final Class<POJOCLASS> clasz, final Provider<EntityManager> entityManagerProvider) {

		super(clasz, entityManagerProvider);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected void updateObjectInternal(final POJOCLASS object, final POJOCLASS updateObject, final EntityManager entityManager)
			throws DMPPersistenceException {

		final String name = object.getName();

		updateObject.setName(name);
	}
}
